cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://localhost:5000
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  application:
    name: rest-conexa-challenger
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Descomentar se for rodar localmente, sem ser por docker
    url: jdbc:mysql://localhost:3308/rest-conexa-challenger?useTimezone=true&serverTimezone=UTC&useSSL=false

    # Deixar Comentado se for rodar localmente sem ser por docker
#    url: jdbc:mysql://db:3306/rest-conexa-challenger?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: docker
    password: admin123
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
#     Descomentar se for rodar localmente sem ser por docker
    url: jdbc:mysql://localhost:3308

    # Deixar Comentado se for rodar localmente sem ser por docker
#    url: jdbc:mysql://db:3306/
    schemas: rest-conexa-challenger 
    user: docker
    password: admin123
    locations: classpath:db/migration
  data:
    redis:
      # Descomentar se for rodar localmente sem ser por docker
      host: localhost

     # Comentar se for rodar localmente sem ser por docker
#      host: redis
      
      port: 6379
springdoc:
  pathsToMatch: 
    - /auth/**
    - /api/v1/**
  swagger-ui:
    use-root-path: true